export const PROJECT_CATEGORIES = [
  "Arts & Crafts",
  "Music & Performance",
  "Writing & Media",
  "Film & Photography",
  "Education & Mentoring",
  "Community Impact",
  "Food & Hospitality",
  "Health & Wellness",
  "Sports & Recreation",
  "Events & Organizing",
  "Entrepreneurship",
  "Design",
  "Sustainability",
  "Research",
  "Creative",
  "Web Development",
  "Mobile Development",
  "AI / Machine Learning",
  "Data Science",
  "Game Development",
  "Open Source",
  "Technology",
  "Other",
];
