export const TECHNOLOGY_LIST = [
  // Creative & community skills
  "Writing",
  "Editing",
  "Research",
  "Public Speaking",
  "Event Planning",
  "Social Media",
  "Photography",
  "Videography",
  "Graphic Design",
  "Illustration",
  "Music Production",
  "Teaching",
  "Mentoring",
  "Fundraising",
  "Marketing",
  "Project Management",
  "Community Outreach",
  "Cooking",
  "Baking",
  "Fitness Coaching",
  "Organizing",
  "User Research",
  "Content Creation",
  "Copywriting",
  "Canva",
  "Figma",
  "Spreadsheets",
  "Data Analysis",
  "Budgeting",
  "Logistics",
  "Stage Management",
  "Interviewing",
  "Facilitation",
  "Grant Writing",
  "Translation",
  "Gardening",
  "Sustainability",
  "Podcasting",
  "Journalism",
  "Leadership",
  "Customer Service",
  "Video Editing",
  "Web Design",
  // Developer & product skills
  "Programming",
  "React",
  "Next.js",
  "Node.js",
  "Express",
  "MongoDB",
  "PostgreSQL",
  "Python",
  "Java",
  "C++",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Git",
  "GitHub",
  "AWS",
  "Firebase",
  "TensorFlow",
  "PyTorch",
  "Unity",
  "Unreal Engine",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Docker",
  "SQL",
  "Machine Learning",
  "Testing",
  "Accessibility",
];
